### ISSUE TITLE
Configure Springdoc

### ISSUE THREAD

**Issue by josdem** [josdem/shopping-cart-service#2]
**Todo**
As a **user**, I want to integrate [SpringDoc](https://springdoc.org/) **so that** I can have [Open API](https://www.openapis.org/) documentation.

**Acceptance Criteria**
- I have a SpringDoc URL where I can browse endpoints
- I have a link attached in the `readme` file

**References**
- See this project configuration as reference: https://github.com/josdem/status-catcher-service

**Comment by HimanshuGangwarOfficial** [comment]
Do let me know if it is still available.

**Comment by josdem** [comment]
Hi @HimanshuGangwarOfficial , yes it is, I added a new label `ready for development` to avoid confusion.
