### ISSUE TITLE
Implement oauth2 authentication

### ISSUE THREAD

**Issue by josdem** [josdem/shopping-cart-service#8]
As a **user**, I want to incorporate [oauth2](https://oauth.net/2/) **so that** I can generate token and secure our endpoints

**Acceptance Criteria**
- I am able to get a token
- I am able to set a `bearer` token in the header to access the endpoints

**References:**
- https://spring.io/guides/tutorials/spring-boot-oauth2/

**Comment by josdem** [comment]
Hi @HimanshuGangwarOfficial , yes it is, I added a new label `ready for development` to avoid confusion

**Comment by Arihant0408** [comment]
Hey @josdem , Is this feature already assigned to someone else, or is it open for anyone to pick?

**Comment by josdem** [comment]
HI @Arihant0408 yes, it is ready for development, I assigned this ticket to you, let me know if you have any questions. Your collaboration is appreciated it.

**Comment by josdem** [comment]
> Hey @josdem , to be able to generate and introspect tokens for authentication using google's OAuth 2.0 api, we need to have a project created in google api console and we also need to set the redirect_url in it.
> 
> If you are ok with this approach, i can start the development effort and meanwhile you can set up the google project.
> 
> Is there any other approach you want to go with?
> 
> Reference: https://developers.google.com/identity/openid-connect/openid-connect#java

Hi @Arihant0408, Thanks for sending the `openid-connect` link from Google and providing a valid solution. I was thinking of implementing our own authentication server using Oauth 2.0 and Spring Boot, please take a look at this project: https://github.com/josdem/spring-boot-authorization-server 
You can find a client implementation example here: https://github.com/spring-projects/spring-security-samples/tree/main/reactive/webflux/java/oauth2/resource-server 
I hope this makes sense. Happy to answer any question you might have or do a pair programming session to solve this.

**Comment by josdem** [comment]
Hi @Arihant0408, I added a repository on how we can implement a resource server so that you can see how we can secure our endpoints using JWT tokens. https://github.com/josdem/spring-webflux-resource-server let me know if you have any questions.

**Comment by Arihant0408** [comment]
hey @josdem .
From your requirements, i came up with some points on how the OAuth2.0 client credentials flow can be and also have some doubts regarding the same.
Requirements:
1. Able to register a client and generate client id and client secret for the client.
2. Able to generate a access-token using client secret and client id
3. Authorisation server:  to generate the access-token(using client credentials passed as header) and will also to introspect it.
4. API server(shopping-cart-service): This will have the endpoints that i want to protect (for ex: /api/v1/message)
5. I want to protect my rest API's so , need to pass the access-token in header.
6. Client: Lets say i have registered my self as a client
7. Resource server: ??

Doubt: 
In this what will resource server symbolise?
As the resource i want to protect is rest apis of shopping-cart. So isn't the API server(shopping-cart) and Resource server the same in this case?

**Comment by josdem** [comment]
Hello @Arihant0408, here are my answers:

1. I created a new issue with creating user functionality [Able to register a user](https://github.com/josdem/spring-boot-authorization-server/issues/5)
2. Correct
3. Correct
4. Correct
5. Correct
6. Covered by number 1
7. Resource Server [spring-webflux-resource-server](https://github.com/josdem/spring-webflux-resource-server) is just an example, we should protect our endpoints in [shopping-cart-service](https://github.com/josdem/shopping-cart-service)

With those answers, I am hoping it is clear what the requirements are, if not please let me know.

**Comment by Arihant0408** [comment]
Hey @josdem , the doubts are cleared.
Can you now just clear what exactly are within the scope for this Pull Request.
I have a sample activity diagram. Can you once verify this and mention what all do i need to implement for this particular issue raised.

https://excalidraw.com/#json=Oy3GJHY15EhnO-OtuWK2z,PNKGkMEqErxQGzQ008CWEA

**Comment by josdem** [comment]
Hi @Arihant0408, thanks for creating the sequence diagram; it is clear and really helps to understand the expected flow; here are my comments about the PR scope:

**Assumptions:**
1. The user is already registered and has valid credentials
2. Even though we will use a database for storing user credentials, has not been implemented yet; therefore, it  is out of scope
3. Actions defined in steps 8, 9, 10, 11, and 12 happen automatically between `shopping-cart-service` and `authorization-server`

**PR scope:**
6. Get `access-token` using credentials
7. Get request to protected API (Let's do only this controller named: `ProductController`)
   A. https://shopping.josdem.io/products/
   B. https://shopping.josdem.io/products/{sku}
8. Send access token for verification
9. Verifies access token and returns
10. Finds user from DB
11. Returns user's client ID and scope
12. Verifies resource access for the user
13. Returns API resource    

Happy to do a pair programming session if you need to; also feel free to send more questions if the scope is still unclear.
